name = input("Enter A Name: ")
course = input("Enter Course: ")
year_Level = input("Enter Year Level: ")
section = input("Enter Section: ")
university = input("Enter University: ")

print("Hello Im", name)
print("from", section, year_Level, "College student")
print("Currently taking", course)
print("In", university)